org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.19.2
minecraft_version_range=[1.19.2,1.19.3)
forge_version=43.5.2
forge_version_range=[43.5.0,44)
loader_version_range=[43,)

mod_id=surveyors_toolbox
mod_name=Surveyor's Toolbox
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.surveyorstoolbox
mod_authors=diggydwarff
mod_description=Practical surveying tools for measuring distance, area, volume, slopes, boundaries, and interiors, with persistent colored chalk guides for planning builds.
